# Generated by Django 4.0.8 on 2024-05-07 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0002_alter_userprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='selected_country',
            field=models.CharField(default='IN', max_length=5),
        ),
    ]
