# Generated by Django 4.0.8 on 2024-05-07 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0003_userprofile_selected_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='selected_country',
        ),
    ]
