# Generated by Django 4.0.8 on 2024-05-09 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0008_alter_card_card_number_bankaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='account_type',
            field=models.CharField(choices=[('personal', 'Personal'), ('business', 'Business')], default='Personal', max_length=20),
        ),
    ]
