# Generated by Django 4.0.8 on 2024-05-09 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0010_alter_bankaccount_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
