# Generated by Django 4.0.8 on 2024-05-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0011_card_is_primary'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='account_balance',
            field=models.DecimalField(decimal_places=2, default=2000.0, max_digits=10),
        ),
    ]
