# Generated by Django 4.0.8 on 2024-05-09 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0012_card_account_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='default_profile.jpg', upload_to='profile_pics/'),
        ),
    ]
